# Generated by Django 5.2 on 2025-05-09 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='saler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.saler'),
        ),
    ]
